### ISSUE TITLE
M1 Mac lpm not working null

### ISSUE THREAD

**Issue by todddube** [alfredapp/low-power-mode-workflow#6]
### Workflow version

v2023.3

### Alfred version

5.1.2 [2145]

### macOS version

macOS Sonoma 14.0 Beta 5

### Debugger output

```alfred_debugger
[14:10:15.126] Logging Started...
[14:10:22.609] Low Power Mode[Script Filter] Queuing argument '(null)'
[14:10:22.673] Low Power Mode[Script Filter] Script with argv '(null)' finished
[14:10:22.679] ERROR: Low Power Mode[Script Filter] Code 1: /Users/myname/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/BF6DAB9B-7F0B-42CE-B6E9-69AB0AA32B11: execution error: Error: TypeError: null is not an object (evaluating 'batteryMatch[1]') (-2700)
```

### More details

constantly  won't work - removed and reinstalled a few times.. tried again today so logging an issue.

**Comment by vitorgalvao** [comment]
* What Mac model are you running it on?
* Does your computer have a battery?
* Are you running it on a Virtual Machine?
* What’s the output of the following command [in a terminal](https://support.apple.com/en-gb/guide/terminal/apd5265185d-f365-44cb-8b09-71a064a42125/mac)? `/usr/bin/pmset -g custom`

**Comment by todddube** [comment]
@vitorgalvao 

- Mac Model: Apple M1 MacBook Pro Max

- Battery: yes

- VM: No - 

- Output: pmset

Battery Power:
 Sleep On Power Button 1
 powermode            0
 standby              1
 ttyskeepawake        1
 hibernatemode        3
 powernap             1
 hibernatefile        /var/vm/sleepimage
 displaysleep         2
 womp                 0
 networkoversleep     0
 sleep                1
 lessbright           1
 tcpkeepalive         1
 disksleep            10
AC Power:
 Sleep On Power Button 1
 powermode            0
 standby              1
 ttyskeepawake        1
 hibernatemode        3
 powernap             1
 hibernatefile        /var/vm/sleepimage
 displaysleep         10
 womp                 1
 networkoversleep     0
 sleep                1
 tcpkeepalive         1
 disksleep            10

**Comment by vitorgalvao** [comment]
Pro and Max chips [have different settings](https://github.com/alfredapp/low-power-mode-workflow/issues/4), including an `Automatic` and don’t have a clear toggle mode so aren’t supported. See the linked issue for more details.
